[package]
name = "solana-perf"
version = "1.8.17"
description = "Solana Performance APIs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-perf"
edition = "2018"

[dependencies]
bincode = "1.3.1"
curve25519-dalek = { version = "2" }
ahash = "0.7.6"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.0"
serde = "1.0.126"
solana-logger = { path = "../logger", version = "=1.8.17" }
solana-metrics = { path = "../metrics", version = "=1.8.17" }
solana-sdk = { path = "../sdk", version = "=1.8.17" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.8.17" }
solana-bloom = { path = "../bloom", version = "=1.8.17" }
solana-vote-program = { path = "../programs/vote", version = "=1.8.17" }

[target."cfg(target_os = \"linux\")".dependencies]
caps = "0.5.3"
libc = "0.2.81"
nix = "0.22.2"

[lib]
name = "solana_perf"

[dev-dependencies]
matches = "0.1.6"

[[bench]]
name = "sigverify"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
